name: bookly
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  path_provider: ^2.0.5
  sqflite: ^2.3.0
  get: ^4.6.6
  chat_gpt_sdk: ^2.2.5
  shared_preferences: ^2.2.2
  document_file_save_plus: ^2.0.0
  fluttertoast: ^8.1.1
  provider: ^6.0.5
  sqflite_common_ffi: ^2.3.0+2
  http: ^1.1.0
  http_parser: ^4.0.2
  path: ^1.8.3
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
